const ALL_SKILLS = [
  // Programming Languages
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Kotlin",
  "Swift",
  "PHP",
  "Ruby",
  "Dart",
  "Scala",
  "R",
  "Groovy",
  "Julia",
  "Prolog",
  "Lisp",
  "Scheme",
  "Clojure",
  "Haskell",
  "OCaml",
  "F#",
  "Assembly",
  "Objective-C",
  "Zig",
  "Nim",
  "Crystal",
  "V",
  "D",
  "Bash",
  "Shell",
  "PowerShell",
  "Perl",
  "Lua",
  "Awk",
  "Tcl",
  "GDScript",
  "Haxe",
  "ActionScript",
  "COBOL",
  "Fortran",
  "Ada",
  "Pascal",
  "Delphi",
  "Smalltalk",
  "RPG",
  "Solidity",
  "Vyper",
  "Move",
  "Cairo",
  "Verilog",
  "VHDL",
  "Brainfuck",
  "Whitespace",
  "Malbolge",
  "Scratch",
  "Red",
  "Ring",
  "Monkey C",
  "FoxPro",

  // Markup / Styling / Config
  "HTML",
  "CSS",
  "Sass",
  "Less",
  "YAML",
  "JSON",
  "HCL",
  "Nix",

  // Frontend Frameworks
  "React",
  "Next.js",
  "Vue.js",
  "Nuxt.js",
  "Angular",
  "Svelte",
  "SolidJS",
  "Qwik",
  "Astro",

  // State Management
  "Redux",
  "Redux Toolkit",
  "Zustand",
  "Recoil",
  "MobX",
  "Jotai",
  "TanStack Query (React Query)",

  // UI / Styling
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Chakra UI",
  "Ant Design",
  "ShadCN UI",
  "Radix UI",
  "Styled Components",
  "CSS Modules",
  "PostCSS",
  "Framer Motion",

  // Backend & APIs
  "Node.js",
  "Express.js",
  "NestJS",
  "Fastify",
  "Hono",
  "REST APIs",
  "GraphQL",
  "WebSockets",
  "tRPC",
  "gRPC",

  // Databases
  "SQL",
  "PL/SQL",
  "T-SQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "Redis",
  "Firebase",
  "Supabase",

  // ORMs
  "Prisma",
  "Drizzle ORM",
  "Sequelize",
  "TypeORM",
  "Mongoose",

  // Auth & Security
  "JWT Authentication",
  "OAuth",
  "Auth0",
  "Clerk",
  "NextAuth",
  "Session Management",
  "RBAC",
  "CSRF Protection",
  "CORS",

  // DevOps & Cloud
  "Docker",
  "Docker Compose",
  "CI/CD",
  "GitHub Actions",
  "Vercel",
  "Netlify",
  "AWS",
  "Azure",
  "Google Cloud",
  "Nginx",
  "PM2",

  // Testing
  "Jest",
  "Vitest",
  "Playwright",
  "Cypress",
  "React Testing Library",
  "Unit Testing",
  "Integration Testing",
  "E2E Testing",

  // Tooling
  "Vite",
  "Webpack",
  "Babel",
  "ESLint",
  "Prettier",
  "TurboRepo",
  "Nx",

  // Performance & Web Concepts
  "Code Splitting",
  "Lazy Loading",
  "Server Side Rendering (SSR)",
  "Static Site Generation (SSG)",
  "Incremental Static Regeneration (ISR)",
  "Caching Strategies",
  "CDN Optimization",
  "SEO",
  "Accessibility (a11y)",
  "Responsive Design",
  "Progressive Web Apps (PWA)",
  "Web Performance",
  "Cross-Browser Compatibility",

  // Version Control
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Code Reviews",

  // CMS & Integrations
  "Headless CMS",
  "Strapi",
  "Sanity",
  "Contentful",
  "WordPress (Headless)",
  "Stripe",
  "Razorpay",
  "PayPal",
  "Webhooks",

  // Monitoring
  "Sentry",
  "LogRocket",
  "Google Analytics",
  "Prometheus",

  // Architecture
  "MVC Architecture",
  "Monolithic Architecture",
  "Modular Monolith",
  "Microservices",
  "Clean Architecture",
  "Design Patterns",

  // AI / ML
  "Machine Learning",
  "Deep Learning",
  "Supervised Learning",
  "Unsupervised Learning",
  "Reinforcement Learning",
  "Feature Engineering",
  "Model Evaluation",
  "Hyperparameter Tuning",
  "Artificial Neural Networks (ANN)",
  "Convolutional Neural Networks (CNN)",
  "Recurrent Neural Networks (RNN)",
  "LSTM",
  "Transformers",
  "Data Preprocessing",
  "Exploratory Data Analysis (EDA)",
  "Data Visualization",
  "Statistical Analysis",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-learn",
  "OpenCV",
  "NLTK",
  "spaCy",
  "Computer Vision",
  "Natural Language Processing (NLP)",
  "Speech Recognition",
  "Recommendation Systems",
  "Time Series Analysis",
  "Model Deployment",
  "ML Pipelines",
  "Model Monitoring",
  "Experiment Tracking",
  "MLflow",
  "Docker for ML",
  "Bias & Fairness in AI",
  "Explainable AI (XAI)",
  "Ethical AI",

  // Mechanical
  "Engineering Mechanics",
  "Strength of Materials",
  "Thermodynamics",
  "Fluid Mechanics",
  "Heat Transfer",
  "Theory of Machines",
  "Machine Design",
  "Manufacturing Processes",
  "CNC Machining",
  "Casting",
  "Welding",
  "Sheet Metal Design",
  "Injection Molding",
  "AutoCAD",
  "SolidWorks",
  "CATIA",
  "Creo",
  "ANSYS",
  "Finite Element Analysis (FEA)",
  "Quality Control",
  "Lean Manufacturing",
  "Six Sigma",
  "Industrial Engineering",
  "Production Planning",
  "Automotive Systems",
  "HVAC Systems",
  "Mechatronics",
  "Robotics",
  "Preventive Maintenance",
  "Failure Analysis",
  "Reliability Engineering",

  // Electronics / ECE / ENTC
  "Analog Electronics",
  "Digital Electronics",
  "Electronic Devices & Circuits",
  "Microelectronics",
  "Analog Communication",
  "Digital Communication",
  "Wireless Communication",
  "Optical Communication",
  "Satellite Communication",
  "Embedded Systems",
  "Microcontrollers",
  "ARM Architecture",
  "RTOS",
  "Signals and Systems",
  "Digital Signal Processing (DSP)",
  "Image Processing",
  "VLSI Design",
  "CMOS Technology",
  "FPGA",
  "ASIC Design",
  "SystemVerilog",
  "Simulink",
  "Xilinx Vivado",
  "Cadence",
  "Computer Networks",
  "IoT Systems",
  "Electronic Instrumentation",
  "Sensors & Actuators",
  "Telecommunication Systems",
  "Mobile Communication",
  "5G Technologies",
  "Network Planning",
  "RF Engineering",
  "Microwave Engineering",
  "IoT Architecture",
  "Industrial IoT",
  "SCADA Systems",
  "Control Systems",
  "PCB Design",
  "Circuit Simulation",
  "Hardware Debugging",
  "Oscilloscope & Logic Analyzer",
  "LabVIEW",
  "Proteus",
  "Multisim",
];

export { ALL_SKILLS };
